[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# What even is a latios bro
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
        G.GAME.hands[hand].mult = math.max(G.GAME.hands[hand].s_mult + G.GAME.hands[hand].l_mult*(G.GAME.hands[hand].level - 1), 1)
'''
position = "before"
payload = '''
if next(SMODS.find_card('j_wowzas_latios')) and amount > 0 then
  for i = 1, #SMODS.find_card('j_wowzas_latios') do
    G.GAME.hands[hand].s_mult = G.GAME.hands[hand].s_mult + SMODS.find_card('j_wowzas_latios')[i].ability.extra.mult_mod*amount
  end
end
if next(SMODS.find_card('j_wowzas_mega_latios')) and amount > 0 then
  for i = 1, #SMODS.find_card('j_wowzas_latios') do
    G.GAME.hands[hand].s_mult = G.GAME.hands[hand].s_mult + SMODS.find_card('j_wowzas_mega_latios')[i].ability.extra.mult_mod*amount
  end
end
'''
match_indent = true

# Okay so latias works too
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
        G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)
'''
position = "before"
payload = '''
if next(SMODS.find_card('j_wowzas_latias')) and amount > 0 then
  for i = 1, #SMODS.find_card('j_wowzas_latias') do
    G.GAME.hands[hand].s_chips = G.GAME.hands[hand].s_chips + SMODS.find_card('j_wowzas_latias')[i].ability.extra.chips*amount
  end
end
if next(SMODS.find_card('j_wowzas_mega_latias')) and amount > 0 then
  for i = 1, #SMODS.find_card('j_wowzas_latias') do
    G.GAME.hands[hand].s_chips = G.GAME.hands[hand].s_chips + SMODS.find_card('j_wowzas_mega_latias')[i].ability.extra.chips*amount
  end
end
'''
match_indent = true
